version: "3.8"
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "80:80"
    depends_on:
      - django
