# Generated by Django 5.2.12 on 2026-03-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0007_alter_applicant_id_alter_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
